[package]
name = "mywasm"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.mrubyedge]
# path = "../mrubyedge"
version = "0.1.1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"